name: Auto Label
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    uses: RokctAI/shared-workflows/.github/workflows/universal-labeler.yml@3ad81fe42b9302f6601510bb8902aab8fa7613e7 # main
    permissions: write-all
    secrets: inherit
