name: Auto Label
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    uses: RokctAI/shared-workflows/.github/workflows/universal-labeler.yml@0baa82d350e5ad1bc8d3950c1417c320fd347c7b # main
    permissions: write-all
    secrets: inherit
