name: License Eye
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1
on:
  pull_request:

jobs:
  license:
    uses: RokctAI/shared-workflows/.github/workflows/universal-license.yml@09494edd4824cc6fca95ea96a2db4d238c4561b3 # shared-workflows main @ 2026-08-26
    permissions: write-all
    secrets: inherit
