name: Semantic PR
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic:
    uses: RokctAI/shared-workflows/.github/workflows/universal-semantic.yml@6c22598ecd6a654f40d83ebb704763da5190b9a0 # main
    permissions: write-all
    secrets: inherit
