name: Welcome Bot
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    uses: RokctAI/shared-workflows/.github/workflows/universal-welcome.yml@0baa82d350e5ad1bc8d3950c1417c320fd347c7b # main
    permissions: write-all
    secrets: inherit
